on:
  push:
    branches: [main]

  # Allow manual triggering of this workflow
  workflow_dispatch:

  # Run this workflow once per year
  schedule:
    - cron: '0 0 1 1 *'

# Ensure only the latest job runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

# Grant this job the permissions required to deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Generate build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Generate and upload build artifacts
        uses: withastro/action@v5

  deploy:
    needs: build

    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
